name: Kontrol CI Demo

on: 
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    concurrency: kontrol-ci-demo
    strategy:
      fail-fast: true

    name: Kontrol Demo Project
    runs-on: [self-hosted, linux, normal]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Kontrol
        uses: runtimeverification/install-kontrol@v1.0.0
        with:
          version: latest

      - name: Run Kontrol Tests
        run: |
          ./run-kontrol.sh
